#!/bin/sh


#git clone $1 "$(basename "$1")"
git clone "$1"

filename=$(basename ":$1")
file="${filename%.*}"

cd $file

#Downloading mlhhooks.py
wget https://github.com/juanli16/McHacks2018/blob/master/mlhhooks.py
#inject it inside .git/hooks/
mv mlhhooks.py .git/hooks/
dir=".git/hooks"
touch $dir/pre-push
echo "#!/bin/sh" > $dir/pre-push
echo "python mlhhooks.py" > $dir/pre-push
echo "exit 0" > $dir/pre-push

chmod +x $dir/pre-push

