#!/bin/sh


#git clone $1 "$(basename "$1")"
git clone "$1"

filename=$(basename ":$1")
file="${filename%.*}"

cd $file

#Downloading mlhhooks.py
wget https://raw.githubusercontent.com/juanli16/McHacks2018/master/mlhhooks.py > /dev/null 2>&1
#inject it inside .git/hooks/
mv mlhhooks.py .git/hooks/
dir=".git/hooks"
touch $dir/pre-push
echo "#!/bin/sh" >> $dir/pre-push
echo 'echo "Using mlhooks.py soon"' >> $dir/pre-push
echo 'FILE="$PWD/.git/hooks"' >> $dir/pre-push
echo 'cd $FILE' >> $dir/pre-push
echo 'python2 mlhhooks.py' >> $dir/pre-push
echo "exit 0" >> $dir/pre-push

chmod +x $dir/pre-push

